version: '3.7'

services:
  app:
    image: your_docker_id/rails_app:v1
    build:
      context: .
    command: ["spring", "server"]
    volumes:
      - app_src:/usr/src/app
      - ${HOME}/.irb-history:/root/.irb-history
      - ${HOME}/.irbrc:/root/.irbrc
      - gems:/usr/local/bundle
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - REDIS_HOST=redis
      - SIDEKIQ_ENABLED=true
      - RAILS_ENV

  web:
    image: your_docker_id/rails_app:v1
    command: ["rails", "server", "--pid=/tmp/server.pid"]
    volumes:
      - app_src:/usr/src/app
      - gems:/usr/local/bundle
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - REDIS_HOST=redis
      - SIDEKIQ_ENABLED=true
      - RAILS_ENV
    ports:
      - 3000:3000

  sidekiq:
    image: your_docker_id/rails_app:v1
    command: ["sidekiq"]
    volumes:
      - app_src:/usr/src/app
      - gems:/usr/local/bundle
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - REDIS_HOST=redis
      - SIDEKIQ_ENABLED=true
      - RAILS_ENV

  redis:
    image: redis:4.0

  pg:
    image: postgres:10.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret

  syncer:
    image: ssync/ssync:0.2.2
    command: watch
    volumes:
      - ./:/src:cached
      - app_src:/dest
      - sync_data:/unison_data
    environment:
      - UNISON_OPTS=-ignore "Path tags*" -ignore "Name {.*,*}.sw[pon]" -ignore "Path tmp/*" -ignore "Path .git" -ignore "Path log/*" -ignore "Path node_modules"

volumes:
  pg-data:
  gems:
  sync_data:
  app_src:
